# Generated by Django 3.2 on 2021-05-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210409_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='siteName',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
